[package]
name = "contrail"
version = "0.1.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
edition = "2018"

[dependencies]
contrail-derive = { path = "../contrail-derive/" }

[dev-dependencies]
rand = "0.6.1"
